version: '3'

tasks:
  default:
    - npm run dev

  build:
    - nix build .#frontend
  
  install:
    - npm ci
  
  update:
    - npm install
    - elm2nix convert > elm-srcs.nix && elm2nix snapshot
