name: backend
version: 0.1.0.0
author: "Pablo Bollansée"
maintainer: "pablo@pabloproductions.be"
license: NONE
copyright: "2023 Pablo Bollansée"

dependencies:
  - base >= 4.16.4.0 && < 5

ghc-options:
  - -Wall
  - -Wcompat # Shows warning that will in the future will be enabled by default
  - -Wincomplete-record-updates
  - -with-rtsopts=-N
  - -Wredundant-constraints
  - -Wunused-packages
  - -Werror
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -freverse-errors

language: GHC2021

default-extensions:
  - StrictData

library:
  source-dirs: src
  dependencies:
    - aeson
    - servant-server
    - text
    - warp

executables:
  backend-exe:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - backend
  
  elm-gen:
    main: Main.hs
    source-dirs: elm-gen
    dependencies:
      - backend
      - elm-bridge
      - servant-elm
      - servant-foreign
      - servant-server
      - text

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - backend
      - QuickCheck
      - servant-client
      - sydtest
      - sydtest-servant
