name: backend
version: 0.1.0.0
author: "Pablo Bollansée"
maintainer: "pablo@pabloproductions.be"
license: NONE
copyright: "2023 Pablo Bollansée"

dependencies:
  - base >= 4.16.4.0 && < 5

ghc-options:
  - -Wall
  - -Wcompat # Shows warning that will in the future will be enabled by default
  - -Wincomplete-record-updates
  - -with-rtsopts=-N
  - -Wredundant-constraints
  - -Wunused-packages
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -freverse-errors

language: GHC2021

default-extensions:
  - StrictData

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - autodocodec-openapi3
    - fakedata
    - openapi3
    - servant-server
    - text
    - unordered-containers
    - warp

executables:
  backend-exe:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - backend

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson-pretty
      - backend
      - QuickCheck
      - servant-client
      - servant-openapi3
      - sydtest
      - sydtest-servant
      - text
