version: '3'

sources: &sources
  - '**/*.hs'
  - package.yaml

tasks:
  default:
    aliases: [test-and-run]
    cmds:
      - task: regen-open-api
      - task: test
      - task: run

  test:
    cmds:
      - stack test --test-arguments="--match=""{{.MATCH}}"""
    sources: *sources
  
  run:
    cmds:
      - pkill backend-exe || true # Kill existing backend if it's still running, Task should already do that, but apparently not: https://github.com/go-task/task/issues/160
      - stack run backend-exe
    sources: *sources
  
  golden-test-reset:
    cmds:
      - stack test --test-arguments="--golden-reset --golden-start"
    sources: *sources

  regen-open-api:
    cmds:
      - stack test --test-arguments="--golden-reset --match \"OpenAPI schema\""
    sources: *sources
